language: node_js
node_js:
  - 9.10.0
cache: yarn
install:
  - npm install
before_script:
  - npm run test:coverage
script:
  - CI=false yarn build
  - npm run build-storybook
before_deploy:
  - git config --global user.email "demey.emmanuel@gmail.com"
  - git config --global user.name "Emmanuel DEMEY"
  - export GIT_TAG=$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://${TRAVIS_SECURE_TOKEN_NAME}@github.com/$TRAVIS_REPO_SLUG --tags
  - tar -zcf ${TRAVIS_BUILD_NUMBER}.tar.gz build

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure:
      - ${TRAVIS_SECURE_TOKEN_NAME}
  file:
    - ${TRAVIS_BUILD_NUMBER}.tar.gz
  on:
    all_branches: true
    condition: '$TRAVIS_BRANCH =~ ^master$'
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - bash scripts/gitbook.sh
